name: machtrac
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  modal_progress_hud:
  double_back_to_close:
  file_picker:
  firebase_storage:
  form_field_validator:
  http:
  geocoding:
  geolocator:
  url_launcher:
  shared_preferences:
  image_picker: any
  google_sign_in: any
  font_awesome_flutter: ^9.0.0
  qrscan:
  mailer:
  provider:
  flare_splash_screen: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf

  assets:
    - assets/welcome_image.png